"use server";

import { createOpenAI } from "@ai-sdk/openai";
import { generateObject } from "ai";
import { z } from "zod";
import prismaDB from "@/lib/prisma";
import * as mammoth from "mammoth";
import { screenDealSchema } from "@/lib/schemas";

const openai = createOpenAI({
  apiKey: process.env.AI_API_KEY,
  compatibility: "strict",
});

export default async function screenDeal(formData: FormData) {
  const file = formData.get("file") as File;
  const comment = formData.get("comment") as string;
  const dealId = formData.get("dealId") as string;

  if (!file || !dealId) {
    throw new Error("File and deal ID are required");
  }

  // Check if the file is a text or docx file
  let fileContent = "";
  if (file.name.endsWith(".txt")) {
    // For text files, use file.text()
    fileContent = await file.text();
  } else if (file.name.endsWith(".docx")) {
    // For docx files, use mammoth to extract the text
    const arrayBuffer = await file.arrayBuffer(); // Get ArrayBuffer
    const buffer = Buffer.from(arrayBuffer); // Convert ArrayBuffer to Node.js Buffer
    const { value } = await mammoth.extractRawText({ buffer });
    fileContent = value;
  } else {
    throw new Error("Unsupported file type");
  }

  console.log("file contents", fileContent);
  // Fetch deal details
  const deal = await prismaDB.deal.findUnique({
    where: { id: dealId },
  });

  if (!deal) {
    throw new Error("Deal not found");
  }

  const { object: aiReasoning } = await generateObject({
    model: openai("gpt-4o"),
    system:
      "You are an AI assistant that screens deals based on provided criteria.",
    prompt: `
      Screen the following deal against the provided criteria:

      Deal Details:
      ${JSON.stringify(deal, null, 2)}

      Screening Criteria:
      ${fileContent}

      Additional Comment:
      ${comment}

      Provide a detailed analysis of the deal based on the screening criteria.
    `,
    schema: screenDealSchema,
  });

  return aiReasoning;

  // return a dummy response for testing
  // return {
  //   title: "AI Reasoning",
  //   explanation: "This is a dummy AI reasoning generated by the OpenAI API.",
  //   sentiment: "positive",
  // };
}
