import { z } from "zod";

export const InferDealSchema = z.object({
  sourceWebsite: z
    .string()
    .describe("The link of the origin of the deal listing.")
    .optional()
    .nullable(),
  brokerage: z
    .string()
    .describe(
      "The brokerage associated with the deal or the name of the site from which the deal was scraped. For example:- BizBuySell",
    )
    .optional()
    .nullable(),
  firstName: z
    .string()
    .describe(
      "The first name of the person who listed the deal or is associated with the deal.",
    )
    .optional()
    .nullable(),
  lastName: z
    .string()
    .describe(
      "The last name of the person who listed the deal or is associated with the deal",
    )
    .optional()
    .nullable(),
  email: z
    .string()
    .describe(
      "The email of the person who listed the deal or is associated with the deal",
    )
    .optional()
    .nullable(),
  companyLocation: z
    .string()
    .describe("The location of the company.")
    .optional()
    .nullable(),
  dealCaption: z
    .string()
    .describe("A detailed explanation of the deal and all its particulars")
    .optional()
    .nullable(),
  industry: z
    .string()
    .describe(
      "The industry to which the deal belongs to. For example:- Healthcare",
    )
    .optional()
    .nullable(),
  askingPrice: z
    .number()
    .describe("The asking price of the deal (e.g., '$15,500,000').")
    .optional()
    .nullable(),
  revenue: z
    .number()
    .describe("The revenue generated by the deal (e.g., '$9,000,000').")
    .optional()
    .nullable(),
  grossRevenue: z
    .number()
    .describe("The grossRevenue generated by the deal (e.g., '$9,000,000').")
    .optional()
    .nullable(),
  ebitda: z
    .number()
    .describe("The EBITDA generated by the deal (e.g., '$25,000,000').")
    .optional()
    .nullable(),
  ebitdaMargin: z
    .number()
    .describe("The EBITDA margin present in the deal (e.g., '0.34%').")
    .optional()
    .nullable(),
  title: z.string().describe("The title of the deal."),
});
