import EditDealForm from "@/components/forms/edit-deal-form";
import PreviousPageButton from "@/components/PreviousPageButton";
import { Card, CardContent } from "@/components/ui/card";
import { fetchSpecificManualDeal } from "@/lib/firebase/db";
import { Metadata } from "next";
import React from "react";

type Params = Promise<{ uid: string }>;

export async function generateMetadata({
  params,
}: {
  params: Params;
}): Promise<Metadata> {
  const { uid } = await params;

  try {
    const fetchedDeal = await fetchSpecificManualDeal(uid);
    return {
      title: `Edit ${fetchedDeal?.title}` || "Dark Alpha Capital",
      description:
        `Edit ${fetchedDeal?.main_content}` || "Generated by create next app",
    };
  } catch (error) {
    return {
      title: "Not Found",
      description: "The page you are looking for does not exist",
    };
  }
}

const EditManualDealPage = async ({ params }: { params: Params }) => {
  const { uid } = await params;

  const fetchedDeal = await fetchSpecificManualDeal(uid);

  if (!fetchedDeal) {
    return (
      <section className="mt-10 text-center text-xl">Deal not found</section>
    );
  }

  const {
    id,
    first_name,
    last_name,
    direct_phone,
    work_phone,
    title,
    cashFlow,
    under_contract,
    revenue,
    source,
    ebitda,
    link,
    scraped_by,
    asking_price,
    listing_code,
    state,
    category,
    status,
    main_content,
    explanation,
    grossRevenue,
    inventory,
  } = fetchedDeal;

  return (
    <section className="block-space relative">
      <div className="absolute left-8 top-6">
        <PreviousPageButton />
      </div>
      <div className="narrow-container mb-8 md:mb-10 lg:mb-12">
        <h1 className="mb-4 text-center text-4xl font-bold text-gray-900">
          Edit Deal: {title}
        </h1>
        <p className="text-center text-lg leading-relaxed text-gray-600">
          You are currently editing the details of the{" "}
          <strong>{category}</strong> deal titled <strong>{title}</strong>.
        </p>
        <p className="text-center text-lg leading-relaxed text-gray-600">
          Please ensure that all fields, such as revenue, asking price,
          location, and contract status, are updated accurately. Once
          you&apos;re done, click on{" "}
          <span className="font-semibold">Save Changes</span> to apply your
          updates. Be mindful that your changes will impact the overall
          visibility and status of this deal in the system.
        </p>
      </div>
      <div className="big-container">
        <Card className="transition-all duration-75 ease-in-out hover:shadow-lg">
          <CardContent className="p-6">
            <EditDealForm
              dealCollection="manual-deals"
              title={title}
              first_name={first_name}
              last_name={last_name}
              direct_phone={direct_phone}
              work_phone={work_phone}
              under_contract={under_contract}
              revenue={revenue}
              link={link}
              asking_price={asking_price}
              listing_code={listing_code}
              state={state}
              status={status}
              main_content={main_content}
              explanation={explanation}
              id={id}
              ebitda={ebitda}
              category={category}
              grossRevenue={grossRevenue}
              inventory={inventory}
            />
          </CardContent>
        </Card>
      </div>
    </section>
  );
};

export default EditManualDealPage;
